### ISSUE TITLE
can i just input some images to build 3Dmodel by using this code?

### ISSUE THREAD

**Issue by raderqi** [zhizdev/sparsefusion#10]
Hi,

I am wondering if I have a series of images from different perspectives, can I use your code for 3D reconstruction?

If this is allowed , what work do I need to do before inputting these images?

thanks for the help!

**Comment by zhizdev** [comment]
If you have many (10+) images from different perspectives, I would try out Instant NGP and nerf2mesh (https://github.com/ashawkey/nerf2mesh).
