### ISSUE TITLE
How to extract the geometry

### ISSUE THREAD

**Issue by ThanTT** [zhizdev/sparsefusion#12]

**Comment by ThanTT** [comment]
Hi, I found that the mesh results are included in the paper, how to extract the geometry results? Thank you for the help and hope for your reply!

**Comment by zhizdev** [comment]
Hey! We use marching cubes (https://github.com/pmneila/PyMCubes) on Instant NGP densities with thresholding to extract the geometry.

**Comment by ThanTT** [comment]
Thanks for your reply!
