### ISSUE TITLE
Availability of Training Code 

### ISSUE THREAD

**Issue by LeeDoYup** [zhizdev/sparsefusion#2]
Hello Thanks for awesome project and the release of pretrained model and evaluation code.
By the way, I wanna ask you whether the training code will be released or not, since I'm highly interested in reproducing the results in the original paper.

**Comment by zhizdev** [comment]
Thanks for reaching out! We plan on releasing training code by mid-year 2023. Meanwhile, we would be happy to chat about the training procedure here, over email, or via video call.

**Comment by zhizdev** [comment]
Closing since early access training code has been released.
