### ISSUE TITLE
Can not find ckpt_latest_eft.pt

### ISSUE THREAD

**Issue by TimenoLong** [zhizdev/sparsefusion#20]
![}09SK$OCQ IL_B{ 7@N$BNQ](https://github.com/zhizdev/sparsefusion/assets/74199560/d0c60a36-472c-4361-b111-39fa675a7580)
Is there a link to download ckpt_latest_eft.pt? Thanks.

**Comment by zhizdev** [comment]
hi -- sorry for the delayed response but the checkpoint can be found on the link in the readme page https://drive.google.com/drive/u/2/folders/1Czsnf-PVjwH-HL7K5mTt_kF9u-PVWRyL
