### ISSUE TITLE
Creating a dataloader for custom data

### ISSUE THREAD

**Issue by hadillivvy** [zhizdev/sparsefusion#21]
You mentioned that for custom data, the dataloader must return the below from its __getitem__ implementation:
`{
  'images': (B, 3, H, W) image tensor,
  'R': (B, 3, 3) PyTorch3D rotation,
  'T': (B, 3) PyTorch3D translation,
  'f': (B, 2) PyTorch3D focal_length in NDC space,
  'c': (B, 2) PyTorch3D principal_point in NDC space,
  'valid_region': (B, 1, H, W) binary tensor where 1 denotes valid image region,
  'image_size': (B, 2) image size
}`

If I'm using relpose++ (https://github.com/amyxlase/relpose-plus-plus) to get the R and T for each image, how can I get the other required fields for each image?

**Comment by zhizdev** [comment]
hey! assuming you give a square image to relpose++, you can use that image as the image tensor and assume principal point is at the center of the sensor (0, 0) and search for a focal length that works well (assuming you don't have the ground truth focal length).
