### ISSUE TITLE
pixelnerf implementation

### ISSUE THREAD

**Issue by zlaskar** [zhizdev/sparsefusion#6]
Hello Authors,

Thanks for the excellent codebase. Is it possible to share files and other codes required to adapt pixelnerf to co3d? 

Really appreciate the effort.

Best

**Comment by zhizdev** [comment]
Hey! We recommend referring to the official pixelnerf repo for pixelnerf code. If you would like additional help getting started with pixelnerf on CO3D / PyTorch3D, feel free to send me an email at zhizhuo@cmu.edu.
