### ISSUE TITLE
Questions about training from scratch

### ISSUE THREAD

**Issue by ff98li** [zhizdev/sparsefusion#9]
Hi, thank you for the amazing work! I'm very interested in applying SparseFusion to my own dataset, so I started off with playing around with the CO3Dv2 first, but got a few questions during training. I have followed the instruction in [ENVIRONMENT.md](https://github.com/zhizdev/sparsefusion/blob/main/ENVIRONMENT.md) to set up the virtual environment prior to starting training.
1. I was trying training for the hotdog category in CO3Dv2 using 2-view input on a `V100` GPU. Below is the terminal output during the first stage of training (EFT+VLDM):
![sparsefusion_train](https://user-images.githubusercontent.com/55061801/235771173-5a3c33d4-8909-4a95-a43a-88153c661fa1.PNG)
The `total training seq 101` confused me in the first place, as I assumed the model was instance-specific and had set `num_input` (which corresponds to `context_size`) to `2` in the training script. Besides `training seq`, the total training time appeared to be about 50 hours, which is much more than it is supposed to be, but after looking at the visualized results for the first few iterations:
![train_000800](https://user-images.githubusercontent.com/55061801/235776664-6297f90e-5034-4a3d-8365-8778229a4f5f.jpg)
![train_001100](https://user-images.githubusercontent.com/55061801/235776712-cf41e951-124f-43f7-8de1-a1ad1b165b77.jpg)
where the first two visualized inputs are the 2-view context, the first `pred` is the EFT-predicted image, and the second `pred` is the VLDM-predicted image. I observed that these are two different instances from the hotdog category, so _I wonder if the model is training on multiple instances of the category at the same time._ If this is the case, are there any suggestions to make the model train on a single instance instead? I have been struggling with comprehending the `CO3Dv2Wrapper` dataset's code as I'm rather new to CO3D, and any tips from the author will be significant help.

2. A follow-up question from the previous one: since the 3D model reconstruction is instance-specific, _does this mean the training of VLDM and EFT will also only use the 2-view input images of a single object instance, rather than involving the views of other object instances from the same class?_

I have read through the paper and the code, but still not 100% sure if my understanding was correct. Your help in unraveling my confusion will greatly appreciated :pray:

Thank you again for the effort and the code release!

**Comment by zhizdev** [comment]
Hi, thanks for checking out our code base!

1. `total training seq 101` refers to the 101 training sequences in the hotdog category. During per category training, we iterate through multiple instances of the category. total training time seems high but it is not necessary to finish the training before having a reasonable model. 
2. VLDM and EFT are trained on a category using all instances of a category. During reconstruction, we freeze VLDM and EFT and use the 2-view input images to fit a NeRF. However, VLDM and EFT already have learned information about the category. 

Feel free to provide more details on what experiment you want to run i.e. whether it is training on N instances of a category or 1 instance of one category and I can try to provide more help!

**Comment by ff98li** [comment]
> Hi, thanks for checking out our code base!
> 
> 1. `total training seq 101` refers to the 101 training sequences in the hotdog category. During per category training, we iterate through multiple instances of the category. total training time seems high but it is not necessary to finish the training before having a reasonable model.
> 2. VLDM and EFT are trained on a category using all instances of a category. During reconstruction, we freeze VLDM and EFT and use the 2-view input images to fit a NeRF. However, VLDM and EFT already have learned information about the category.
> 
> Feel free to provide more details on what experiment you want to run i.e. whether it is training on N instances of a category or 1 instance of one category and I can try to provide more help!

Thank you so much for the prompt reply! I truly appreciate it. This has addressed all the concerns I have so far. I will open a new issue once I have further questions. 🙏

**Comment by xiaoyaozaixmu** [comment]
Hi, I am preparing to retrain this EFT and VLDM weights, but I am experiencing the following:
 ModuleNotFoundError: No module named 'co3d'
Can you tell me what settings you did for co3d for retraining?

**Comment by xiaoyaozaixmu** [comment]
Also, hello, may I ask how you downloaded the file for one of the items in co3dv2。thank you
